display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
                title: Pubblicato
              2:
                title: 'Non pubblicato'
            label: 'Stato pubblicazione'
          expose:
            label: Stato
        title:
          expose:
            label: Titolo
        type:
          expose:
            label: 'Tipo di contenuto'
        langcode:
          expose:
            label: Lingua
      exposed_form:
        options:
          submit_button: Filtra
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_asc_label: Asc
          sort_desc_label: Disc
      pager:
        options:
          tags:
            previous: '‹ Precedente'
            next: 'Seguente ›'
            first: '« Prima'
            last: 'Ultima »'
      fields:
        title:
          label: Titolo
        type:
          label: 'Tipo di contenuto'
          separator: ', '
        name:
          label: Autore
        status:
          label: Stato
          settings:
            format_custom_true: Pubblicato
            format_custom_false: 'Non pubblicato'
        changed:
          label: Aggiornato
        operations:
          label: Operazioni
      title: Contenuto
      empty:
        area_text_custom:
          content: 'Nessun contenuto disponibile.'
    display_title: Principale
  page_1:
    display_options:
      menu:
        title: Contenuto
      tab_options:
        title: Contenuto
        description: 'Trova e gestisci contenuti'
    display_title: Pagina
label: Contenuto
description: 'Trova e gestisci contenuti.'
