display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: ۱
                title: 'منتشر شده'
              2:
                title: 'منتشر نشده'
          expose:
            label: صحیح
        bundle:
          expose:
            label: ارائه‌دهنده
        langcode:
          expose:
            label: زبان
      exposed_form:
        options:
          submit_button: اعمال
          reset_button_label: بازنشانی
          exposed_sorts_label: 'مرتب کن بر اساس'
          sort_asc_label: صعودی
          sort_desc_label: نزولی
      pager:
        options:
          expose:
            items_per_page_label: 'آیتم‌ها در هر صفحه'
            items_per_page_options_all_label: '- همه -'
            offset_label: جابجایی
      fields:
        thumbnail__target_id:
          label: 'تصویر بندانگشتی'
        bundle:
          label: ارائه‌دهنده
        uid:
          label: نویسنده
        status:
          label: وضعیت
          settings:
            format_custom_true: 'منتشر شده'
            format_custom_false: 'منتشر نشده'
        changed:
          label: به‌روز
        operations:
          label: کارکردها
      title: رسانه
      empty:
        area_text_custom:
          content: 'هیچ محتوایی در دسترس نیست.'
    display_title: مدیر
  media_page_list:
    display_title: رسانه
    display_options:
      menu:
        title: رسانه
label: رسانه
