entity_print.settings:
  type: config_object
  label: 'Entity Print settings.'
  mapping:
    default_css:
      type: boolean
      label: 'Enable the default CSS.'
    force_download:
      type: boolean
      label: 'Force download of Print'
    print_engines:
      type: sequence
      label: 'All in-use print engines.'
      sequence:
        type: string

entity_print.print_engine.*:
  type: config_entity
  label: 'Print Engine'
  mapping:
    id:
      type: string
      label: 'Print Engine Id'
    settings:
      type: entity_print_print_engine.[%parent.id]
      label: 'Settings for the Print Engine.'

entity_print_print_engine.dompdf:
  type: mapping
  label: 'Dompdf specific settings'
  mapping:
    default_paper_size:
      type: string
      label: 'Default Paper Size'
    enable_html5_parser:
      type: boolean
      label: 'Enable HTML5 parsing'
    enable_remote:
      type: boolean
      label: 'Enable remote urls'
    cafile:
      type: string
      label: 'Path to the cafile'
    verify_peer:
      type: boolean
      label: 'Verify Peer'
    verify_peer_name:
      type: boolean
      label: 'Verify Peer Name'

entity_print_print_engine.phpwkhtmltopdf:
  type: mapping
  label: 'PHP Wkhtmltopdf'
  type: mapping
  mapping:
    binary_location:
      type: string
      label: 'Path to the wkhtmltopdf binary'

entity_print_print_engine.tcpdfv1:
  type: mapping
  label: 'TCPDF (v1)'
  type: mapping
  mapping:
    page_format:
      type: string
      label: 'The page format. E.g. A3, A4 or many more options'
    orientation:
      type: string
      label: 'One of Landscape or Portrait'

# Add schema for our extra field settings.
core.entity_view_display.*.*.*.third_party.entity_print:
  type: sequence
  label: 'Schema for Entity Print third party settings'
  sequence:
    type: string
    label: 'Entity print settings for each export type'

action.configuration.entity_print_download_action:
  type: action_configuration_default
  label: 'Print Action'

field.formatter.settings.entity_print_base64_image_formatter:
  type: mapping
  label: 'Image field display format settings'
  mapping:
    image_style:
      type: string
      label: 'Image style'
