display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
                title: 공개
          expose:
            label: 참
        bundle:
          expose:
            label: 제공자
        langcode:
          expose:
            label: 언어
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
      fields:
        bundle:
          label: 제공자
        uid:
          label: 글쓴이
        status:
          label: 상태
          settings:
            format_custom_true: 공개
        changed:
          label: 갱신됨
        operations:
          label: 작업
      title: 미디어
      empty:
        area_text_custom:
          content: '콘텐츠가 없습니다.'
    display_title: 마스터
  media_page_list:
    display_title: 미디어
    display_options:
      menu:
        title: 미디어
label: 미디어
