label: 'Δείτε την σελίδα επεξεργασίας'
tips:
  views-main:
    label: 'Επεξεργαστείτε τις ρυθμίσεις προβολής'
    body: 'Δείτε ή επεξεργαστείτε τις ρυθμίσεις.'
  views-ui-displays:
    label: 'Εμφανίσεις σε αυτό το view'
    body: 'Μια εμφάνιση είναι ένας τρόπος να προβάλλουμε τα αποτελέσματα, πχ σαν μια σελίδα ή ένα μπλοκ. Ένα view μπορεί να εμπεριέχει πολλαπλές εμφανίσεις , οι οποίες παρουσιάζονται εδώ. Η ενεργή εμφάνιση έχει επισημανθεί.'
  views-ui-view-admin:
    body: 'Εκτελέστε διαχειριστικές εργασίες, συμπεριλαμβανομένων της προσθήκης περιγραφής και της δημιουργίας ενός κλόνου. Πατήστε το κουμπί της αναδυόμενης λίστας για να δείτε τις διαθέσιμες επιλογές.'
  views-ui-format:
    label: 'Μορφή εξόδου'
  views-ui-fields:
    label: Πεδία
    body: 'Εάν αυτό το view χρησιμοποιεί πεδία, παραθέτονται εδώ. Μπορείτε να πατήσετε σε ένα πεδίο για να το παραμετροποιήσετε.'
  views-ui-filter:
    label: 'Φιλτράρετε το view σας'
    body: 'Προσθέτει φίλτρα για να περιορίσει τα αποτελέσματα. Για παράδειγμα, εάν θέλετε να δείξετε περιεχόμενο που είναι <em>δημοσιευμένο</em>, προσθέστε ένα φίλτρο για <em>Δημοσιευμένο</em> και επιλέξτε <em>Ναι</em>.'
  views-ui-filter-operations:
    label: 'Φιλτράρισμα ενεργειών'
    body: 'Προσθήκη, αναδιάρθρωση ή διαγραφή φίλτρων.'
  views-ui-sorts:
    label: 'Κριτήρια Ταξινόμησης'
    body: 'Ελέγξτε τη σειρά με την οποία προβάλονται τα αποτελέσματα. Πατήστε σε έναν ενεργό κανόνα διάταξης για να την παραμετροποιήσετε.'
  views-ui-sorts-operations:
    label: 'Ταξινόμηση ενεργειών'
    body: 'Προσθήκη, αναδιάρθρωση ή διαγραφή κανόνων ταξινόμησης.'
  views-ui-preview:
    label: Προεπισκόπηση
    body: 'Προβολή προεπισκόπησης του αποτελέσματος του view.'
