label: 'Επεξεργασία γλωσσών'
tips:
  language-edit-overview:
    label: 'Επεξεργασία γλωσσών'
    body: '<p>Αυτή η σελίδα παρέχει τη δυνατότητα επεξεργασίας μιας γλώσσας στον ιστότοπό σας, συμπεριλαμβανομένων προσαρμοσμένων γλωσσών.</p>'
  language-edit-langcode:
    label: 'Κωδικός γλώσσας'
    body: '<p>Δεν μπορείτε να αλλάξετε τον κωδικό μιας γλώσσας στον ιστότοπο, εφόσον χρησιμοποιείται από το σύστημα για τον έλεγχο της γλώσσας.</p>'
  language-edit-label:
    label: 'Όνομα γλώσσας'
  language-edit-direction:
    label: 'Κατεύθυνση γλώσσας'
    body: '<p>Επιλέξτε εάν η κατεύθυνση της γλώσσας είναι “Αριστερά προς δεξιά” ή “Δεξιά προς αριστερά”.</p><p>Προσέξτε ότι δεν υποστηρίζουν όλες οι θεματικές παραλλαγές διάταξη “Δεξιά προς αριστερά”, οπότε ελέγξτε τη θεματική σας παραλλαγή εάν χρησιμοποιείτε τέτοια διάταξη.</p>'
