label: Γλώσσα
tips:
  language-overview:
    label: Γλώσσες
    body: '<p>Η σελίδα "Γλώσσες" σας επιτρέπει να προσθέσετε, επεξεργαστείτε, διαγράψετε και να αναδιατάξετε γλώσσες για τον ιστότοπο.</p>'
  language-add:
    label: 'Προσθήκη γλωσσών'
    body: '<p>Για να προσθέσετε περισσότερες γλώσσες στον ιστοτόπο σας, πατήστε το κουμπί "Προσθήκη γλώσσας".</p><p>Οι γλώσσες που έχουν προστεθεί θα εμφανιστούν στη λίστα γλωσσών και στη συνέχεια είναι δυνατή η επεξεργασία ή η διαγραφή τους.</p>'
  language-reorder:
    label: 'Αναδιάταξη γλωσσών'
  language-default:
    label: 'Ορισμός μιας γλώσσας ως προεπιλεγμένη'
  language-operations:
    label: 'Τροποποίηση γλωσσών'
