label: Μετάφραση
tips:
  locale-overview:
    label: 'Μετάφραση διεπαφής χρήστη'
  locale-language:
    label: 'Γλώσσα μετάφρασης'
    body: 'Επιλέξτε τη γλώσσα που θέλετε να μεταφράσετε.'
  locale-search:
    label: Αναζήτηση
    body: 'Εισάγετε την ακριβή λέξη ή πρόταση που θέλετε να μεταφράσετε, μπορείτε επίσης να γράψετε μόνο ένα μέρος μιας λέξης.'
  locale-filter:
    label: 'Φιλτράρισμα της αναζήτησης'
  locale-submit:
    label: 'Εφαρμογή των κριτηρίων αναζήτησής σας'
    body: 'Για να εφαρμόσετε τα κριτήρια αναζήτησής σας, πατήστε το κουμπί <em>Φίλτρο</em>.'
  locale-translate:
    label: Μετάφραση
  locale-validate:
    label: 'Επαληθεύστε τη μετάφραση'
