label: Traducción
tips:
  locale-overview:
    label: 'Traducción de la interfaz de usuario'
  locale-language:
    label: 'Translation language'
    body: 'Elija el idioma que quiere traducir.'
  locale-search:
    label: Buscar
    body: 'Enter the specific word or sentence you want to translate, you can also write just a part of a word.'
  locale-filter:
    label: 'Filtrar la búsqueda'
    body: 'Puede buscar cadenas no traducidas si quiere traducir algo que todavía no está traducido. Si quiere modificar una traducción exitente, podría querer buscar solo cadenas traducidas.'
  locale-submit:
    label: 'Aplicar su criterio de búsqueda'
    body: 'Para aplicar su criterio de búsqueda, haga click en el botón <em>Filtrar</em>.'
  locale-translate:
    label: Traducir
    body: 'Puede escribir su propia traducción en los campos de texto en la columna de la derecha. Intente fijarse en cual contexto el texto será usado para traducirlo de la manera apropiada.'
  locale-validate:
    label: 'Validar la traducción'
    body: 'Cuando haya terminado sus traducciones, haga clic en el botón <em>Guardar traducciones</em>. Usted debe guardar sus traducciones, cada vez antes de cambiar de página o hacer una nueva búsqueda.'
  locale-continue:
    label: 'Continuing on'
