display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
                title: Activo
              2:
                title: Blocked
            label: Estado
        combine:
          expose:
            label: 'Nombre o correo contienen'
        roles_target_id:
          expose:
            label: Rol
        permission:
          expose:
            label: Permission
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
      fields:
        user_bulk_form:
          label: 'Actualización en masa'
        name:
          label: 'Nombre de usuario'
        status:
          label: Estado
          settings:
            format_custom_true: Activo
            format_custom_false: Blocked
        roles_target_id:
          label: Roles
        created:
          label: 'Member for'
        access:
          label: 'Último acceso'
        operations:
          label: Operaciones
        mail:
          separator: ', '
      title: Usuarios
      empty:
        area_text_custom:
          content: 'No people available.'
      use_more_text: más
    display_title: Máster
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Lista
        description: 'Encontrar y gestionar qué personas interactúan con su sitio.'
      tab_options:
        title: Usuarios
        description: 'Manage user accounts, roles, and permissions.'
label: Usuarios
description: 'Encontrar y gestionar qué personas interactúan con su sitio.'
