label: Perfiles
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      arguments:
        uid:
          exception:
            title: Todo
        type:
          exception:
            title: Todo
        status:
          exception:
            title: Todo
      title: Perfiles
  user_view:
    display_title: 'Vista de usuario'
