label: 'Página principal'
description: 'Todo el contenido promovido a la página principal.'
display:
  default:
    display_options:
      empty:
        area_text_custom:
          content: 'Todavía no se ha creado contenido para la portada.'
        title:
          title: 'Bienvenido a [site:name]'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Previous'
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
    display_title: Máster
  feed_1:
    display_title: Agregador
  page_1:
    display_title: Página
