display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
      filters:
        type:
          expose:
            label: Tipo
        title:
          expose:
            label: Título
      sorts:
        created:
          expose:
            label: Fecha
