label: 'Sindicador de canal denoticias RSS'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Previous'
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
      fields:
        iid:
          label: 'ID de elemento'
      title: 'Sindicador de canal denoticias RSS'
  feed_items:
    display_title: Agregador
