label: 'Fuentes del sindicador'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Previous'
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
      title: Fuentes
  feed_1:
    display_title: Agregador
    display_options:
      fields:
        title:
          separator: ', '
      title: 'Canal de noticias OPML'
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Fuentes
