display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
                title: Publié
              2:
                title: 'Non publié'
            label: 'Statut de publication'
          expose:
            label: Vrai
        bundle:
          expose:
            label: Fournisseur
        langcode:
          expose:
            label: Langue
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
      fields:
        thumbnail__target_id:
          label: Vignette
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Fournisseur
          separator: ', '
        uid:
          label: Auteur
          separator: ', '
        status:
          label: Statut
          settings:
            format_custom_true: Publié
            format_custom_false: 'Non publié'
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        operations:
          label: Actions
      title: Média
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
    display_title: Maître
  media_page_list:
    display_title: Média
    display_options:
      menu:
        title: Média
label: Média
