label: 视图编辑页面
tips:
  views-main:
    label: 管理视图设置
    body: 查看或修改配置。
  views-ui-displays:
    label: 此视图包含的显示样式
  views-ui-view-admin:
    label: 视图管理
    body: 执行管理任务，包括添加描述和创建克隆。点击下拉按钮查看可选选项。
  views-ui-format:
    label: 输出格式
  views-ui-fields:
    label: 字段
    body: 如果该视图使用了字段，其字段将显示在此处。您可以点击任一字段对其进行配置。
  views-ui-filter:
    label: 过滤您的视图
    body: 添加过滤条件以限制输出结果。如，要只显示<em>已发布</em>的内容，您可以添加一个<em>已发布</em>的过滤条件，并选择<em>是</em>.
  views-ui-filter-operations:
    label: 过滤动作
    body: 添加，重新排列或者移除过滤条件。
  views-ui-sorts:
    label: 排序准则
    body: 控制结果输出顺序.点击一个活跃的排序规则配置它.
  views-ui-sorts-operations:
    label: 排序动作
    body: 添加、重新排列或者移除排序规则
  views-ui-preview:
    label: 预览
    body: 显示视图输出的预览。
