label: 语言
tips:
  language-overview:
    label: 语言
    body: '<p>"语言 (Languages)" 页面允许您为站点添加、修改、删除或者排序语言。</p>'
  language-add:
    body: '<p>要为您的站点添加更多语言，点击“添加语言”按钮。</p><p>您添加的语言将会显示在语言列表中，并可以编辑或删除。</p>'
  language-reorder:
    label: 更改语言的顺序
  language-default:
    label: 将语言设置为默认
  language-operations:
    label: 修改语言
  language-continue:
    label: 接下来
