cancel_confirm:
  subject: '[site:name] 上 [user:display-name] 帐户取消请求。'
password_reset:
  subject: '[site:name] [user:display-name] 更换登录信息.'
register_admin_created:
  body: "[user:display-name]，\r\n\r\n[site:name] 的管理员为您创建了一个帐户。您可以点击下面的链接登录，或者把它复制到浏览器地址栏：\r\n\r\n[user:one-time-login-url]\r\n\r\n此链接只能用于登录一次，它会带您到一个页面让您来设置您的密码。\r\n\r\n设置了密码之后，您以后就可以在 [site:login-url] ，使用如下信息登录：\r\n\r\n用户名： [user:name]\r\n密码： 您设置的密码\r\n\r\n--  [site:name] 团队"
  subject: '一个站点管理员为您在 [site:name] 上创建了一个账户'
register_no_approval_required:
  body: "[user:display-name]，\r\n\r\n谢谢您在 [site:name] 注册。您现在可以点击下面的链接登录，或者把它复制到浏览器地址栏：\r\n\r\n[user:one-time-login-url]\r\n\r\n此链接只能用于登录一次，它会带您到一个页面让您来设置您的密码。\r\n\r\n设置了密码之后，您以后就可以在 [site:login-url] ，使用如下信息登录：\r\n\r\n用户名： [user:name]\r\n密码： 您设置的密码\r\n\r\n--  [site:name] 团队"
  subject: '账户信息 [user:display-name] 在 [site:name]'
register_pending_approval:
  body: "[user:display-name],\r\n\r\n感谢您在 [site:name] 注册. 您申请的账户正在等待审批. 一旦通过审批,您将收到一封电子邮件内容包括如何登录, 设置密码等.\r\n\r\n\r\n--  [site:name] 团队"
  subject: '账户信息 [user:display-name] 在 [site:name] (待审批)'
register_pending_approval_admin:
  body: "[user:display-name] 申请了一个帐户。\r\n\r\n[user:edit-url]"
  subject: '账户信息 [user:display-name] 在 [site:name] (待审批)'
status_activated:
  body: "[user:display-name]，\r\n\r\n您在 [site:name] 的帐户已经激活。\r\n\r\n您可以点击下面的链接登录，或者把它复制到浏览器地址栏：\r\n\r\n[user:one-time-login-url]\r\n\r\n此链接只能用于登录一次，它会带您到一个页面让您来设置您的密码。\r\n\r\n设置了密码之后，您以后就可以在 [site:login-url] ，使用如下信息登录：\r\n\r\n用户名： [user:account-name]\r\n密码： 您设置的密码\r\n\r\n--  [site:name] 团队"
  subject: '帐号信息 [user:display-name] 在 [site:name] (核对成功)'
status_blocked:
  subject: '帐号信息 [user:display-name] 在 [site:name] (已冻结)'
status_canceled:
  body: "[user:display-name],\r\n\r\n你的帐号在网站 [site:name] 已被取消。\r\n\r\n--  [site:name] 团队"
  subject: '帐号信息 [user:display-name] 在 [site:name] (已注销)'
