label: 媒体
display:
  default:
    display_title: 主
    display_options:
      exposed_form:
        options:
          submit_button: 应用
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      pager:
        options:
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
          tags:
            previous: '‹ 上一个'
            next: '下一个 ›'
            first: '« 首页'
            last: '末页 »'
      fields:
        thumbnail__target_id:
          label: 缩略图
          separator: '， '
        name:
          separator: '， '
        bundle:
          label: 提供者
          separator: '， '
        uid:
          label: 作者
          separator: '， '
        status:
          label: 状态
          separator: '， '
        changed:
          label: 已更新
          separator: '， '
        operations:
          label: 操作
      filters:
        status:
          expose:
            label: 真
          group_info:
            label: 发布状态
            group_items:
              1:
                title: 已发表
                value: '1'
              2:
                title: 未发布
        bundle:
          expose:
            label: 提供者
        langcode:
          expose:
            label: 语言
      title: 媒体
      empty:
        area_text_custom:
          content: 没有可用的内容。
  media_page_list:
    display_title: 媒体
    display_options:
      menu:
        title: 媒体
