features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/default/files/purtle_logo.png
favicon:
  use_default: true
  path: core/themes/bartik/purtle_favicon.ico
  mimetype: image/vnd.microsoft.icon
