palette:
  base: '#3753ae'
  bg: '#7ea6fb'
  left: '#04206c'
  right: '#2c64fc'
  headerborders: '#7ea6fb'
  text: '#3b3b3b'
  link: '#1948d2'
  highlight: '#a8bdeb'
  pagetitle: '#3a51a1'
  pagetitletext: '#f1f1f1'
  menudivider: '#689add'
  node: '#d1deff'
  nodeborders: '#f0f4ff'
  nodedivider: '#869bca'
  stickynode: '#a8c2ff'
  tableheader: '#5385df'
  even: '#b8caf9'
  sidebar: '#a8c2ff'
  sidebarborders: '#bdd0ff'
  sidebardivider: '#8199ca'
  sidebartext: '#434343'
  sidebarlink: '#0f71ff'
  footer: '#232f61'
  footertext: '#cccccc'
  footerlink: '#78adfc'
  titleslogan: '#ffffff'
logo: 'public://color/mayo-e204c250/logo.svg'
stylesheets:
  - 'public://color/mayo-e204c250/colors.css'
files:
  - 'public://color/mayo-e204c250/logo.svg'
  - 'public://color/mayo-e204c250/colors.css'
