palette:
  top: '#4545ba'
  bottom: '#131458'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071B3'
logo: 'public://color/bartik-65cbe320/logo.svg'
stylesheets:
  - 'public://color/bartik-65cbe320/colors.css'
files:
  - 'public://color/bartik-65cbe320/logo.svg'
  - 'public://color/bartik-65cbe320/colors.css'
