content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  student: 3
  translator: 4
  administrator: 5
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_node_type:
  assignment: 'a:2:{s:8:"view_own";a:2:{i:0;s:7:"student";i:1;s:13:"administrator";}s:4:"view";a:2:{i:0;s:7:"student";i:1;s:13:"administrator";}}'
  audio: 'a:3:{s:8:"view_own";a:1:{i:0;s:13:"administrator";}s:4:"view";a:1:{i:0;s:13:"administrator";}s:8:"per_node";i:1;}'
