module:
  acl: 0
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  aggregator: 0
  audiofield: 0
  automated_cron: 0
  backup_migrate: 0
  ban: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_place: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  content_access: 0
  content_browser: 0
  content_moderation: 0
  content_translation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  db_maintenance: 0
  dblog: 0
  droogle: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  ds: 0
  ds_extras: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_print: 0
  entity_print_views: 0
  entity_reference: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  language: 0
  languageicons: 0
  layout_plugin: 0
  layout_plugin_example: 0
  libraries: 0
  link: 0
  locale: 0
  media_entity: 0
  media_entity_audio: 0
  media_entity_image: 0
  menu_ui: 0
  node: 0
  node_clone: 0
  options: 0
  page_cache: 0
  path: 0
  profile: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  rules: 0
  search: 0
  search404: 0
  shortcut: 0
  simple_sitemap: 0
  statistics: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  terms_of_use: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  tracker: 0
  typed_data: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
