title_text: 'Droogle: A list of your google docs'
client_id: 315360126701-bglje2b1592cvjmm1jrlsjmsa3l2bh16.apps.googleusercontent.com
client_secret: 7Jz5TsFXV5mTC3XbyD291PG3
droogle_redirect_callback: droogle
