session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    pt-br: pt-br
    el: el
    fa: fa
    zh-hans: zh-hans
    fr: fr
    it: it
    ja: ja
    ko: ko
  domains:
    en: ''
    es: ''
    pt-br: ''
    el: ''
    fa: ''
    zh-hans: ''
    fr: ''
    it: ''
    ja: ''
    ko: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
